package com.baishan.greendaodemo.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.baishan.greendaodemo.model.Animal;
import com.baishan.greendaodemo.model.User;

import com.baishan.greendaodemo.dao.AnimalDao;
import com.baishan.greendaodemo.dao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig animalDaoConfig;
    private final DaoConfig userDaoConfig;

    private final AnimalDao animalDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        animalDaoConfig = daoConfigMap.get(AnimalDao.class).clone();
        animalDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        animalDao = new AnimalDao(animalDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Animal.class, animalDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        animalDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public AnimalDao getAnimalDao() {
        return animalDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
